<?php

namespace AppBundle\Repository;

/**
 * CalmodeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalmodeloRepository extends \Doctrine\ORM\EntityRepository
{
}
