<?php

namespace AppBundle\Repository;

/**
 * ClasificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasificacionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * 
    * Devuelve en formato JSON los datos de la tabla
    */
    
    public function listaJSON()
    {
        $arrClasificacion=$this->getEntityManager()
                                ->createQuery('SELECT c.idclasificacion'
                                        . ' ,e.codigo'
                                        . ' ,e.nombres'
                                        . ' ,e.apellidos'
                                        . ' ,c.anio'
                                        . ' ,c.periodo'
                                        . ' ,c.desertor'
                                        . ' FROM AppBundle:Clasificacion c'
                                        . ' JOIN AppBundle:Estudiante e'
                                        . ' WITH c.idestudiante = e.idestudiante')
                                ->getResult();
        
        
        $arrJSON='{'
                . '"draw":1,'
                . '"recordsTotal": '.count($arrClasificacion).','
                . '"recordsFiltered":'.count($arrClasificacion).','
                . '"data": [';
                
        
        for($i=0; $i<count($arrClasificacion); $i++){            
            $arrJSON=$arrJSON. '[';
            $arrJSON=$arrJSON.'"'.$arrClasificacion[$i]["idclasificacion"].'",';
            $arrJSON=$arrJSON.'"'.$arrClasificacion[$i]["codigo"].'",';
            $arrJSON=$arrJSON.'"'.ucwords(strtolower($arrClasificacion[$i]["nombres"])).'",';
            $arrJSON=$arrJSON.'"'.ucwords(strtolower($arrClasificacion[$i]["apellidos"])).'",';
            $arrJSON=$arrJSON.'"'.$arrClasificacion[$i]["anio"].'",';
            $arrJSON=$arrJSON.'"'.$arrClasificacion[$i]["periodo"].'",';
            $arrJSON=$arrJSON.'"'.$arrClasificacion[$i]["desertor"].'",';
            $arrJSON=$arrJSON.'" '
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-success btn-xs\" data-toggle=\"modal\" data-target=\"#vm_actualizar\"'
                    . 'data-idclasificacion=\"'.$arrClasificacion[$i]["idclasificacion"].'\"'
                    . '>'
                    . '<i class=\'glyphicon glyphicon-edit\'>'
                    . '</i> Modificar'
                    . '</button>'
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-danger btn-xs\" data-toggle=\"modal\" data-target=\"#vm_eliminar\"'
                    . 'data-idcaracteristica=\"'.$arrClasificacion[$i]["idclasificacion"].'\"'                    
                    . '>'
                    . '<i class=\'glyphicon glyphicon-trash\'>'
                    . '</i> Eliminar'
                    . '</button>'
                    . '"';             
            if($i==count($arrClasificacion)-1){
                    $arrJSON=$arrJSON.']';
            }
            else{
                $arrJSON=$arrJSON.'],';                           
            }
        }
        $arrJSON=$arrJSON.']';
        
        $arrJSON=$arrJSON.'}';
        
        return($arrJSON);
    }
}
