<?php

namespace AppBundle\Repository;

/**
 * EntrenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrenamientoRepository extends \Doctrine\ORM\EntityRepository
{
}
