<?php

namespace AppBundle\Repository;

/**
 * EntrenamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrenamientoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * 
    * Devuelve en formato JSON los datos de la tabla
    */
    
    public function listaJSON()
    {
        $arrEntrenamiento=$this->getEntityManager()
                                ->createQuery('SELECT 
                                                ent.identrenamiento,
                                                est.codigo Estudiante,
                                                car.descripcion Caracterisitica,
                                                ent.valor,
                                                cla.desertor
                                                FROM AppBundle:Entrenamiento ent
                                                JOIN AppBundle:Clasificacion cla
                                                WITH ent.idclasificacion = cla.idclasificacion
                                                JOIN AppBundle:Caracteristica car
                                                WITH ent.idcaracteristica = car.idcaracteristica
                                                JOIN AppBundle:Estudiante est
                                                WITH cla.idestudiante = est.idestudiante
                                                order by est.codigo,
                                                car.descripcion')
                                ->getResult();
        
        
        $arrJSON='{'
                . '"draw":1,'
                . '"recordsTotal": '.count($arrEntrenamiento).','
                . '"recordsFiltered":'.count($arrEntrenamiento).','
                . '"data": [';
                
        
        for($i=0; $i<count($arrEntrenamiento); $i++){            
            $arrJSON=$arrJSON. '[';
            $arrJSON=$arrJSON.'"'.$arrEntrenamiento[$i]["Estudiante"].'",';
            $arrJSON=$arrJSON.'"'.$arrEntrenamiento[$i]["Caracterisitica"].'",';
            $arrJSON=$arrJSON.'"'.$arrEntrenamiento[$i]["valor"].'",';
            $arrJSON=$arrJSON.'"'.(($arrEntrenamiento[$i]["desertor"]=='1')?'S':'N').'",';
            $arrJSON=$arrJSON.'" '
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-success btn-xs\" data-toggle=\"modal\" data-target=\"#vm_actualizar\"'
                    . 'data-identrenamiento=\"'.$arrEntrenamiento[$i]["identrenamiento"].'\"'
                    . '>'
                    . '<i class=\'glyphicon glyphicon-edit\'>'
                    . '</i> Modificar'
                    . '</button>'
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-danger btn-xs\" data-toggle=\"modal\" data-target=\"#vm_eliminar\"'
                    . 'data-identrenamiento=\"'.$arrEntrenamiento[$i]["identrenamiento"].'\"'                    
                    . '>'
                    . '<i class=\'glyphicon glyphicon-trash\'>'
                    . '</i> Eliminar'
                    . '</button>'
                    . '"';             
            if($i==count($arrEntrenamiento)-1){
                    $arrJSON=$arrJSON.']';
            }
            else{
                $arrJSON=$arrJSON.'],';                           
            }
        }
        $arrJSON=$arrJSON.']';
        
        $arrJSON=$arrJSON.'}';
        
        return($arrJSON);
    }
}
