<?php

namespace AppBundle\Repository;

/**
 * TipousuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipousuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:TipoUsuario p'
            )
            ->getResult();
    }
    
    /**
     * 
     * Devuelve en formato JSON los datos de la tabla
     */
    
    public function listaJSON()
    {
        $arrTipousuario=$this->getEntityManager()
                                ->createQuery('SELECT p FROM AppBundle:TipoUsuario p')
                                ->getResult();
        
        
        $arrJSON='{'
                . '"draw":1,'
                . '"recordsTotal": '.count($arrTipousuario).','
                . '"recordsFiltered":'.count($arrTipousuario).','
                . '"data": [';
                
        
        for($i=0; $i<count($arrTipousuario); $i++){            
            $arrJSON=$arrJSON. '[';
            $arrJSON=$arrJSON.'"'.$arrTipousuario[$i]->getTipousuario().'",';
            $arrJSON=$arrJSON.'"'.$arrTipousuario[$i]->getdescripcion().'",';
            $arrJSON=$arrJSON.'" '
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-success btn-xs\" data-toggle=\"modal\" data-target=\"#vm_actualizar\"'
                    . 'data-tipousuario=\"'.$arrTipousuario[$i]->getTipousuario().'\"'
                    . 'data-descripcion=\"'.$arrTipousuario[$i]->getdescripcion().'\"'
                    . 'data-idtipousuario=\"'.$arrTipousuario[$i]->getIdtipousuario().'\"'
                    . '>'
                    . '<i class=\'glyphicon glyphicon-edit\'>'
                    . '</i> Modificar'
                    . '</button>"';
            
            if($i==count($arrTipousuario)-1){
                    $arrJSON=$arrJSON.']';
            }
            else{
                $arrJSON=$arrJSON.'],';                           
            }
        }
        $arrJSON=$arrJSON.']';
        
        $arrJSON=$arrJSON.'}';
        
        return($arrJSON);
    }
}
