<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * 
    * Devuelve en formato JSON los datos de la tabla
    */
    
    public function listaJSON()
    {
        $arrUsuario=$this->getEntityManager()
                                ->createQuery('SELECT c FROM AppBundle:User c')
                                ->getResult();
        

        $arrJSON='{'
                . '"draw":1,'
                . '"recordsTotal": '.count($arrUsuario).','
                . '"recordsFiltered":'.count($arrUsuario).','
                . '"data": [';
                
        
        for($i=0; $i<count($arrUsuario); $i++){            
            $arrJSON=$arrJSON. '[';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getUsername().'",';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getNombres().'",';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getApellidos().'",';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getIdentificacion().'",';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getEmail().'",';
            $arrJSON=$arrJSON.'"'.$arrUsuario[$i]->getRole().'",';
            $arrJSON=$arrJSON.'" '
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-success btn-xs\" data-toggle=\"modal\" data-target=\"#vm_actualizar\"'
                    . 'data-id=\"'.$arrUsuario[$i]->getId().'\"'
                    . 'data-nombres=\"'.$arrUsuario[$i]->getNombres().'\"'
                    . '>'
                    . '<i class=\'glyphicon glyphicon-edit\'>'
                    . '</i> Modificar'
                    . '</button>'
                    . '<button type=\"button\" id=\"btn\" class=\"btn btn-danger btn-xs\" data-toggle=\"modal\" data-target=\"#vm_eliminar\"'
                    . 'data-id=\"'.$arrUsuario[$i]->getId().'\"'                    
                    . '>'
                    . '<i class=\'glyphicon glyphicon-trash\'>'
                    . '</i> Eliminar'
                    . '</button>'
                    . '"';             
            if($i==count($arrUsuario)-1){
                    $arrJSON=$arrJSON.']';
            }
            else{
                $arrJSON=$arrJSON.'],';                           
            }
        }
        $arrJSON=$arrJSON.']';
        
        $arrJSON=$arrJSON.'}';
        
        return($arrJSON);
    }
}
