<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entrenamiento extends \AppBundle\Entity\Entrenamiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'idestudiante', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c1', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c2', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c3', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c4', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c5', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'identrenamiento', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'estudiantesestudiante'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'idestudiante', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c1', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c2', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c3', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c4', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'c5', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'identrenamiento', '' . "\0" . 'AppBundle\\Entity\\Entrenamiento' . "\0" . 'estudiantesestudiante'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entrenamiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdestudiante($idestudiante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestudiante', [$idestudiante]);

        return parent::setIdestudiante($idestudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestudiante', []);

        return parent::getIdestudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function setC1($c1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC1', [$c1]);

        return parent::setC1($c1);
    }

    /**
     * {@inheritDoc}
     */
    public function getC1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC1', []);

        return parent::getC1();
    }

    /**
     * {@inheritDoc}
     */
    public function setC2($c2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC2', [$c2]);

        return parent::setC2($c2);
    }

    /**
     * {@inheritDoc}
     */
    public function getC2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC2', []);

        return parent::getC2();
    }

    /**
     * {@inheritDoc}
     */
    public function setC3($c3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC3', [$c3]);

        return parent::setC3($c3);
    }

    /**
     * {@inheritDoc}
     */
    public function getC3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC3', []);

        return parent::getC3();
    }

    /**
     * {@inheritDoc}
     */
    public function setC4($c4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC4', [$c4]);

        return parent::setC4($c4);
    }

    /**
     * {@inheritDoc}
     */
    public function getC4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC4', []);

        return parent::getC4();
    }

    /**
     * {@inheritDoc}
     */
    public function setC5($c5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setC5', [$c5]);

        return parent::setC5($c5);
    }

    /**
     * {@inheritDoc}
     */
    public function getC5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getC5', []);

        return parent::getC5();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentrenamiento()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdentrenamiento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentrenamiento', []);

        return parent::getIdentrenamiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstudiantesestudiante(\AppBundle\Entity\Estudiantes $estudiantesestudiante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstudiantesestudiante', [$estudiantesestudiante]);

        return parent::setEstudiantesestudiante($estudiantesestudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudiantesestudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudiantesestudiante', []);

        return parent::getEstudiantesestudiante();
    }

}
