<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Seguimientoestudiante extends \AppBundle\Entity\Seguimientoestudiante implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idacciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idestudiante', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'asignadoa', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idseguimientoestudiante', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'usuariosusuario', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'accionesacciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'estudiantesestudiante'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idacciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idestudiante', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'fechainicio', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'fechafin', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'estado', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'asignadoa', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'idseguimientoestudiante', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'usuariosusuario', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'accionesacciones', '' . "\0" . 'AppBundle\\Entity\\Seguimientoestudiante' . "\0" . 'estudiantesestudiante'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Seguimientoestudiante $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdacciones($idacciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdacciones', [$idacciones]);

        return parent::setIdacciones($idacciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdacciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdacciones', []);

        return parent::getIdacciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestudiante($idestudiante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestudiante', [$idestudiante]);

        return parent::setIdestudiante($idestudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestudiante', []);

        return parent::getIdestudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', [$fechainicio]);

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', []);

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', [$fechafin]);

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', []);

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignadoa($asignadoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignadoa', [$asignadoa]);

        return parent::setAsignadoa($asignadoa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignadoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignadoa', []);

        return parent::getAsignadoa();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdseguimientoestudiante()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdseguimientoestudiante();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdseguimientoestudiante', []);

        return parent::getIdseguimientoestudiante();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariosusuario(\AppBundle\Entity\Usuarios $usuariosusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariosusuario', [$usuariosusuario]);

        return parent::setUsuariosusuario($usuariosusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariosusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariosusuario', []);

        return parent::getUsuariosusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccionesacciones(\AppBundle\Entity\Acciones $accionesacciones = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccionesacciones', [$accionesacciones]);

        return parent::setAccionesacciones($accionesacciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccionesacciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccionesacciones', []);

        return parent::getAccionesacciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstudiantesestudiante(\AppBundle\Entity\Estudiantes $estudiantesestudiante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstudiantesestudiante', [$estudiantesestudiante]);

        return parent::setEstudiantesestudiante($estudiantesestudiante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstudiantesestudiante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstudiantesestudiante', []);

        return parent::getEstudiantesestudiante();
    }

}
