<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \AppBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'identificacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombres', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'contrasena', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idtipousuario', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idtipoidentificacion'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'identificacion', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'nombres', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'contrasena', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idusuario', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idtipousuario', '' . "\0" . 'AppBundle\\Entity\\Usuario' . "\0" . 'idtipoidentificacion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdentificacion($identificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificacion', [$identificacion]);

        return parent::setIdentificacion($identificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificacion', []);

        return parent::getIdentificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombres($nombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombres', [$nombres]);

        return parent::setNombres($nombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombres', []);

        return parent::getNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', [$apellidos]);

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', []);

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrasena($contrasena)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrasena', [$contrasena]);

        return parent::setContrasena($contrasena);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrasena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrasena', []);

        return parent::getContrasena();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipousuario(\AppBundle\Entity\Tipousuario $idtipousuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipousuario', [$idtipousuario]);

        return parent::setIdtipousuario($idtipousuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipousuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipousuario', []);

        return parent::getIdtipousuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipoidentificacion(\AppBundle\Entity\Tipoidentificacion $idtipoidentificacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipoidentificacion', [$idtipoidentificacion]);

        return parent::setIdtipoidentificacion($idtipoidentificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipoidentificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipoidentificacion', []);

        return parent::getIdtipoidentificacion();
    }

}
